# File: .github/workflows/repo-sync.yml
name: Repo-Sync

on:
  schedule:
  - cron:  "*/59 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "dgaspary/fpOdf"
        source_branch: "master"
        destination_branch: "MasterClone"
        github_token: ${{ secrets.GITHUB_TOKEN }}
